# Generated by Django 5.2.7 on 2025-10-21 13:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('employee_id', models.CharField(blank=True, max_length=50)),
                ('department', models.CharField(blank=True, choices=[('it', 'Information Technology'), ('hr', 'Human Resources'), ('finance', 'Finance'), ('operations', 'Operations'), ('sales', 'Sales'), ('marketing', 'Marketing'), ('support', 'Customer Support'), ('other', 'Other')], max_length=20)),
                ('job_title', models.CharField(blank=True, max_length=100)),
                ('office_location', models.CharField(blank=True, max_length=200)),
                ('time_zone', models.CharField(default='UTC', max_length=50)),
                ('avatar', models.ImageField(blank=True, upload_to='avatars/')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('email_notifications', models.BooleanField(default=True)),
                ('ticket_notifications', models.BooleanField(default=True)),
                ('asset_notifications', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_reports', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_key', models.CharField(max_length=40, unique=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('login_time', models.DateTimeField(auto_now_add=True)),
                ('logout_time', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Session',
                'verbose_name_plural': 'User Sessions',
                'ordering': ['-login_time'],
            },
        ),
    ]
